#### pandas
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

Pandas is an open source library providing high performance, easy to use data structures and data analysis tool and it is super important and in data science world everybody used that pandas.

In [1]:
!pip install pandas

In [2]:
import pandas as pd #alias
import numpy as np #alias

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
#create a Dataframe
pd.DataFrame(data=np.arange(0,20).reshape(5,4),columns=['Column1','Column2','Column3','Column4'])

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [5]:
df=pd.DataFrame(
    data=np.arange(0,20).reshape(5,4), #first u have to supply uor data
    index=['Row1','Row2','Row3','Row4','Row5'], #second yoy have to supply custom index name
    columns=['Column1','Column2','Column3','Column4'] #you have to supply custom column name
)

In [6]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
#what is the type of the df
type(df)

pandas.core.frame.DataFrame

In [8]:
df.head() #head() returns by default top 5 records from uor dataframe

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.tail() #tail() returns by default bottom or last 5 records from the dataframe

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df.head(2) #in notebook you just press shift+tab to get that entire information of the dataframe

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [11]:
df.tail(3)

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [12]:
df.describe() #it returns 5 point summary

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [13]:
df[['Column1','Column2']] #

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [14]:
df[['Column1']]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [15]:
type(df[['Column1']]) #type of this particular value also the dataframe, because here one column and 5 rows are there

pandas.core.frame.DataFrame

In [16]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [17]:
type(df['Column1'])

pandas.core.series.Series

In [18]:
#how we can get the data in respect to row index ??
df.loc[["Row1","Row3"]]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row3        8        9       10       11

In [19]:
type(df.loc[["Row1","Row3"]])

pandas.core.frame.DataFrame

In [20]:
type(df.loc[["Row1"]])

pandas.core.frame.DataFrame

In [21]:
#iloc is your index location
#: is your all the records
#df.loc[row,column]
df.iloc[0:3,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11

In [22]:
df.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [23]:
df.iloc[:,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [24]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
#here your index is starting from 0 
df.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [26]:
df.iloc[2:4,1:3]

Column2  Column3
Row3        9       10
Row4       13       14

In [27]:
#here you can convert your dataframe into array with the help of .values
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [28]:
#note : 
#1.whenever we require to retrive the data from row and column wise then we can use df.iloc
#2.whenever we require to retrieve the data only for row ise then we can use .loc
#3. whenever we require to retrive the data only for column wise we can use df[[]]


In [29]:
np.nan #nan basically means null values

nan

In [30]:
df=pd.DataFrame(
    data=[[1,np.nan,2],[1,3,4]],
    index=["Row1","Row2"],
    columns=["Column1","Column2","Column3"]
)

In [31]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [32]:
#feature engineerinf
df=pd.DataFrame(
    data=[[1,np.nan,2],[1,3,4],[5,4,3]],
    index=["Row1","Row2","Row3"],
    columns=["Column1","Column2","Column3"]
)

In [33]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [34]:
df.isnull() #detects missing values

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [35]:
df.isnull().sum() #sum() methods returns the sumnation of null values

Column1    0
Column2    1
Column3    0
dtype: int64

In [36]:
df.isna() #isna() also an alternative of isnull

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [37]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [38]:
type(np.nan) #it showing the type of np.nan is float

float

In [39]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [40]:
df.info() #every information of the dataframe you can get via df.info() method

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [41]:
df.head()

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [42]:
#to check the unique values
df['Column1']

Row1    1
Row2    1
Row3    5
Name: Column1, dtype: int64

In [43]:
df['Column1'].value_counts()
#Note: value_counts() only applied on top of the data series.

1    2
5    1
Name: Column1, dtype: int64

In [46]:
#it takes each and evry rows and fetch the unique values
#df['Column1'].value_counts()
df['Column1'].unique()

array([1, 5], dtype=int64)

In [44]:
df.value_counts()

Column1  Column2  Column3
1        3.0      4          1
5        4.0      3          1
dtype: int64

In [45]:
df['Column2'].value_counts()

3.0    1
4.0    1
Name: Column2, dtype: int64

In [47]:
df['Column1'].nunique()

2

In [50]:
#lets create one example of dataframe
#you can consider its a dictnary
dict1={'A':[1,2,3],'B':[1,1,1]}
df=pd.DataFrame(dict1)

In [52]:
type(dict1)

dict

In [51]:
df

A  B
0  1  1
1  2  1
2  3  1

In [53]:
#unique should not work on top of the dataframe
#and it requires one column name
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [55]:
#inside the column A it calculates the unique values
df['A'].unique()

array([1, 2, 3], dtype=int64)

In [58]:
df.nunique()

A    3
B    1
dtype: int64

In [ ]:
#The axis to use. 0 or 'index' for row-wise, 1 or 'columns' for column-wise.

In [61]:
df.nunique(axis=0) #for us specifc row it will check the unique values. 
#axis=0 it will check row wise

A    3
B    1
dtype: int64

In [60]:
df.nunique(axis=1) #it will check column wise check the unique values.
#it will check axis=1 column wise

0    1
1    2
2    2
dtype: int64

In [56]:
#inside the column B it calculates the unique values
df['B'].unique()

array([1], dtype=int64)

In [57]:
#Count number of distinct elements in specified axis.
df['A'].nunique()

3

In [63]:
df.nunique(axis=0)

A    3
B    1
dtype: int64

In [64]:
df.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [65]:
#now we are going to create one more custom dataframe
df=pd.DataFrame(
  data=np.arange(0,20).reshape(5,4),
  index=["Row1","Row2","Row3","Row4","Row5"],
  columns=["Column1","Column2","Column3","Column4"]
)

In [66]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [67]:
df['Column2']>5

Row1    False
Row2    False
Row3     True
Row4     True
Row5     True
Name: Column2, dtype: bool

In [68]:
df[df['Column2']>5]
#just think it like an sql wise

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [69]:
df[df.isnull()]

Column1  Column2  Column3  Column4
Row1      NaN      NaN      NaN      NaN
Row2      NaN      NaN      NaN      NaN
Row3      NaN      NaN      NaN      NaN
Row4      NaN      NaN      NaN      NaN
Row5      NaN      NaN      NaN      NaN

In [70]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [71]:
#now in this example we are going to see that convert this dataframe into csv, json
#what is the full form of csv=comma seperated value
df.to_csv('test1.csv')

In [74]:
df.to_csv('test1.csv',index=False) #it will not going to consider it row index

In [77]:
#now i am going to convert this dataframe into excel
df.to_excel('test1.xlsx')

In [78]:
#now we can read the excel file
df2=pd.read_excel('test1.xlsx')

In [79]:
df2.head()

Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [75]:
#now after converting your dataframe to csv and there is other function where
#you can also read the csv
df1=pd.read_csv('test1.csv')

In [76]:
df1.head()

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [80]:
#read the csv file from the url
my_url="https://download.bls.gov/pub/time.series/cu/cu.item"
df3=pd.read_csv(my_url,sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [86]:
import requests
import pandas as pd
from io import StringIO

my_url = "https://download.bls.gov/pub/time.series/cu/cu.item"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(my_url, headers=headers)
response.raise_for_status()
# Read CSV from the response content
#df3 = pd.read_csv(StringIO(response.text), sep='\t')
print(response)

HTTPError: 403 Client Error: Forbidden for url: https://download.bls.gov/pub/time.series/cu/cu.item

In [91]:
#how to probaly read the json format data
#json=javascript object notation
#now i am going to create the json
data_json='{"employee_name":"kaushik","email":"kaushik1111@yahoo.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [92]:
data_json

'{"employee_name":"kaushik","email":"kaushik1111@yahoo.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [93]:
type(data_json) 

str

In [94]:
df4=pd.read_json(data_json) #so we can read the data from json format

In [95]:
df4

employee_name                  email  \
0       kaushik  kaushik1111@yahoo.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [96]:
#how to create an additional columns
df4['Experience']=10

In [97]:
pd.read_json(data_json)

employee_name                  email  \
0       kaushik  kaushik1111@yahoo.com   

                                   job_profile  
0  {'title': 'Team Lead', 'role': 'Developer'}

In [98]:
df4.head()

employee_name                  email  \
0       kaushik  kaushik1111@yahoo.com   

                                   job_profile  Experience  
0  {'title': 'Team Lead', 'role': 'Developer'}          10

In [99]:
df5=pd.read_json(data_json,orient="columns") #orientation as per column wise

In [100]:
df5['job_profile']

0    {'title': 'Team Lead', 'role': 'Developer'}
Name: job_profile, dtype: object

In [101]:
#create the data
df=pd.DataFrame(
   [['a','b'],['c','d']],
   index=['row1','row2'],
   columns=['col1','col2']
)

In [102]:
df

col1 col2
row1    a    b
row2    c    d

In [103]:
#convert this dataframe to json format
df.to_json()

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [104]:
df.to_json(orient="records")

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [105]:
df.to_json(orient="columns")

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [108]:
my_another_url="https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

In [112]:
df6=pd.read_csv(my_another_url,header=None)

In [113]:
df6.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [115]:
df6.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [116]:
df7=pd.read_csv(my_another_url)

In [120]:
df7.head()

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   

   1065  
0  1050  
1  1185  
2  1480  
3   735  
4  1450

In [121]:
#create custom color in that cell
#create one dataframe
data={
    'A':np.random.rand(5),
    'B':np.random.rand(5),
    'C':np.random.rand(5)
}

In [122]:
df=pd.DataFrame(data)

In [123]:
df.head()

A         B         C
0  0.031532  0.432171  0.634942
1  0.894865  0.147955  0.547204
2  0.203768  0.922482  0.398189
3  0.844759  0.955058  0.526513
4  0.028259  0.679686  0.198451

In [129]:
#define our custom color coding logic
def color_odd_even(val):
    if val % 2 == 0:
        return 'background-color: #AED6F1'
    else:
        return 'background-color:#FAD02E'

In [130]:
#apply this style to my dataframe
styled_df= df.style.applymap(color_odd_even)

In [131]:
styled_df

In [132]:
styled_df.to_excel('my_custom_style_df.xlsx',index=False)