In [1]:
print("welcome to the numpy session!!!")

welcome to the numpy session!!!


In [2]:
#numpy 
import numpy as np

In [3]:
#this is my lsit
list=[1,2,3,4]
#take np.array
np.array(list)

array([1, 2, 3, 4])

In [4]:
arr= np.array(list)

In [5]:
#check the arr type
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [9]:
arr1=np.array([[1,2,3],[4,5,6]]) # in this array there are 6 elements are present

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape #2 rows and 3 columns and this is 2 dimensions

(2, 3)

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.reshape(3,2) #3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr1.reshape(1,6)  #1*6 || 2 *3 ||  3 *2 || 6*1 

array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
#usecase of tuple with np.array
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#you can see the datatype of this array
arr1.dtype

dtype('int64')

In [20]:
#you can create elements with np.array
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1,10,2) #1, 1+2 =3, 3+2=5, 5+2=7, 7+2=9

array([1, 3, 5, 7, 9])

In [22]:
#now we can check the shape of this array
np.arange(1,10,2).shape

(5,)

In [23]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [25]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [ ]:
dataset
id name age
1  nn    23
2  mm    22
3  ww    12
(3,3)

In [26]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
np.arange(1,20,2).shape

(10,)

In [28]:
np.arange(1,20,2).reshape(2,5) #rows is horizontally and columns are vertically

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [29]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [30]:
range(1,20,2)

range(1, 20, 2)

In [34]:
np.arange(50,1,-2) #reverse order

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [35]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [36]:
np.linspace(1,20,40).shape

(40,)

In [37]:
#with the help of linspace u can create eqaully sapced element
#40 elements between 1 to 20
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [44]:
np.ones((3,5)) #by default floating . i hope is clear

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
5 + np.ones((3,5)) #this is called broad casting operation

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [ ]:
#identity matrix 
#all the diagonal element is 1 and remaining are 0

In [48]:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [51]:
#randmom value with numpy
print("Random number genearation (uniform distribution)")
np.random.rand(2,3) #most of the time the number in between o and 1

Random number genearation (uniform distribution)


array([[0.91968036, 0.27167847, 0.65532682],
       [0.171561  , 0.38392865, 0.04683683]])

In [52]:
print("Random number following a Normal distribution with mean=0 and std=1")

Random number following a Normal distribution with mean=0 and std=1


In [54]:
print(np.random.randn(5,3)) #randn  here used with Normal distribution

[[-0.02419822 -0.6696381   0.11771819]
 [ 1.74030914 -1.31731292  0.11319728]
 [ 1.17313107 -1.47239715  1.26165932]
 [ 0.67789591 -2.37085866  0.66167806]
 [-0.36060827  0.49227124 -1.21099169]]


In [57]:
np.random.randint(1,100) #in between 1 to 100

30

In [58]:
np.random.randint(1,100,10) #10 here elements 

array([52, 19, 76,  1, 59, 22, 82, 58, 16, 43])

In [59]:
np.random.randint(1,100,(4,4))

array([[61, 67, 90, 33],
       [28, 44,  7, 80],
       [97, 29, 12, 25],
       [ 5, 45, 96,  5]])

In [64]:
arr2=np.arange(0,11)

In [65]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing method

In [66]:
#sliceing
#index will start from 0th postion 
#but index in R programming language it will start from 1
arr2[2]

2

In [67]:
arr2[2:] #: means rest of the last thing

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr2[2:7] #from 2 to 7 we want to get tha value

array([2, 3, 4, 5, 6])

In [69]:
arr2[-1] #if i want to get the last element so basically i can add -1

10

In [70]:
arr2[-1:7]

array([], dtype=int64)

In [73]:
arr2[2:7:3]

array([2, 5])

In [71]:
arr2[-1:7:-1] #-1 is the 10th element || :7 is the 7th index || 

array([10,  9,  8])

In [74]:
arr2[-1:7:-1] #negative indexing

array([10,  9,  8])

In [75]:
arr2[-1:3] #-1 is my last element means value is 10 || but forward side there is no other element is present || :-1 means
#it will backwoard side coming

array([], dtype=int64)

In [77]:
arr2[-1:3:-2] #[1,2,3,4,5,6,7,8,9,10] ---> there are no value <----- if i come backward side calculation i probaly
#get the value -2 [10, (10-2),(8-2),(6-2)] [10,8,6,4] # remeber last index nver be calculated

array([10,  8,  6,  4])

In [79]:
arr_new=np.random.randint(2,100,20).reshape(5,4)

In [80]:
arr_new

array([[98, 49, 95,  9],
       [18, 70, 29, 76],
       [66,  6, 59, 57],
       [60, 33, 25, 29],
       [11, 35, 55, 66]])

In [89]:
arr_new[2:4]

array([[66,  6, 59, 57],
       [60, 33, 25, 29]])

In [90]:
arr_new[2:4,1:3]

array([[ 6, 59],
       [33, 25]])

In [91]:
arr_new[-3:-1,-3:-1]

array([[ 6, 59],
       [33, 25]])

### universal functions

In [92]:
#universal functions
arr1=np.random.randint(1,100,(3,3)) #shape will be the same
arr2=np.random.randint(20,100,(3,3))


In [93]:
arr1

array([[36,  4, 66],
       [82, 26, 57],
       [57, 56, 25]])

In [94]:
arr2

array([[72, 92, 91],
       [60, 61, 83],
       [98, 55, 73]])

In [ ]:
#want to add two array is it possible to add or sum it up ?
# the shape of the two arrays will be the same

In [95]:
arr1 + arr2 #you can succesfully add this 2 arrays values

array([[108,  96, 157],
       [142,  87, 140],
       [155, 111,  98]])

In [96]:
arr1 * arr2 #it can multiply the array value

array([[2592,  368, 6006],
       [4920, 1586, 4731],
       [5586, 3080, 1825]])

In [97]:
arr1 / arr2 # we can also divide the array value

array([[0.5       , 0.04347826, 0.72527473],
       [1.36666667, 0.42622951, 0.68674699],
       [0.58163265, 1.01818182, 0.34246575]])

In [98]:
arr1 - arr2 #we also substract the two array values

array([[-36, -88, -25],
       [ 22, -35, -26],
       [-41,   1, -48]])

In [82]:
arr_new[0:3] #3 rows want 

array([[98, 49, 95,  9],
       [18, 70, 29, 76],
       [66,  6, 59, 57]])

In [84]:
arr_new[3:,1:] #first targeting the 3 rows and new next column we use 3:, 1:

array([[33, 25, 29],
       [35, 55, 66]])

In [83]:
arr_new[0:3,0:3] #rows seperately and columns seperatly

array([[98, 49, 95],
       [18, 70, 29],
       [66,  6, 59]])

In [ ]:
arr_new[0:3]

### In built function in numpy

In [99]:
np.sqrt(arr1) #provides the square root of arr1

array([[6.        , 2.        , 8.1240384 ],
       [9.05538514, 5.09901951, 7.54983444],
       [7.54983444, 7.48331477, 5.        ]])

In [100]:
np.exp(arr2)

array([[1.85867175e+31, 9.01762841e+39, 3.31740010e+39],
       [1.14200739e+26, 3.10429794e+26, 1.11286375e+36],
       [3.63797095e+42, 7.69478527e+23, 5.05239363e+31]])

In [101]:
np.log10(arr1)

array([[1.5563025 , 0.60205999, 1.81954394],
       [1.91381385, 1.41497335, 1.75587486],
       [1.75587486, 1.74818803, 1.39794001]])

In [102]:
new_array = np.arange(1,10)

In [103]:
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
new_array[2:]=1000 #what will happen

In [105]:
new_array #after the second index the value will be 1000 || this concept is caleed as broad casting.

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [106]:
np.dot(arr1,arr2) #dot operation

array([[ 9300,  7186,  8426],
       [13050, 12265, 13781],
       [ 9914, 10035, 11660]])

In [107]:
np.matmul(arr1,arr2) #now your matrix multiplication also work || all are inbuilt function

array([[ 9300,  7186,  8426],
       [13050, 12265, 13781],
       [ 9914, 10035, 11660]])

In [ ]:
#numpy is a open source library so, please remeber this thing